 {
        original_params: $original_params,
        save_path: $save_path,
        csp_train: !obj:braindecode.csp.experiment.CSPExperiment {
            set_loader: !obj:braindecode.datasets.set_loaders.$set_type {
                filename: $dataset_filename
            },
            sensor_names: $sensor_names,
            low_cut_off_hz: $low_cut_off_hz,
            cleaner: $cleaner,
            resample_fs: $resample_fs,
            segment_ival: $segment_ival,
            standardize: $standardize,
            n_folds: $n_folds,
            n_top_bottom_csp_filters: $n_top_bottom_csp_filters,
            n_selected_filterbands: $n_selected_filterbands,
            n_selected_features: $n_selected_features,
            forward_steps: $forward_steps,
            backward_steps: $backward_steps,
            min_freq: $min_freq,
            max_freq: $max_freq,
            low_width: $low_width,
            high_width: $high_width,
            last_low_freq: $last_low_freq,          
        }
}
