 {
        layers: $layers,
        original_params: $original_params,
        save_path: $save_path,
        dataset: &dataset $dataset,
        dataset_splitter: &dataset_splitter $dataset_splitter,
        exp_args: {
            preprocessor: &preprocessor $preprocessor,
            iterator: $iterator,
            loss_var_func: $loss_var_func,
            updates_var_func: $updates_var_func,
            monitors: $monitors,
            stop_criterion: !obj:braindecode.veganlasagne.stopping.Or {
                stop_criteria: [
                    !obj:braindecode.veganlasagne.stopping.NoDecrease {
                        chan_name: valid_misclass,
                        num_epochs: $max_increasing_epochs,
                        min_decrease: 0.,
                    },
                    !obj:braindecode.veganlasagne.stopping.MaxEpochs {
                        num_epochs: $max_epochs,
                    },
                ]
            },
        },
}
